# Generated by Django 4.2.5 on 2025-05-16 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('guardian_name', models.CharField(max_length=255)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.class')),
                ('student_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentschool')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedChapterTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.chapter')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentschool')),
                ('topics', models.ManyToManyField(to='v1.topic')),
            ],
        ),
    ]
