# Generated by Django 4.2.5 on 2025-05-16 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_topicprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicprogress',
            name='last_accessed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
