# Generated by Django 4.2.5 on 2025-09-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_initial'),
        ('students', '0003_topicaccesslog_studentloginactivity_topicprogress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.schoolprofile'),
        ),
    ]
