# Generated by Django 4.2.5 on 2025-06-19 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
        ('teachers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='assigned_classes',
            field=models.ManyToManyField(related_name='assigned_teachers', to='v1.classmodel'),
        ),
        migrations.CreateModel(
            name='TeacherNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField(blank=True, null=True)),
                ('note_file', models.FileField(blank=True, null=True, upload_to='teacher_notes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='teachers.teacherprofile')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notes', to='v1.topic')),
            ],
        ),
    ]
