# Generated by Django 4.2.5 on 2025-09-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_studentprofile_school'),
        ('v1', '0002_alter_subject_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_model',
        ),
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='students.studentprofile'),
            preserve_default=False,
        ),
    ]
