# Generated by Django 4.2.5 on 2025-09-25 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_initial'),
        ('v1', '0003_remove_subject_class_model_subject_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='school.schoolprofile'),
        ),
    ]
